"""T-01-08 - Generate deterministic SUMO route files from the scenarios.

Turns each scenario (``config/scenarios/scn_*.yaml``, T-01-01) into one
``.rou.xml`` per ``(scenario, seed)``. Vehicles arrive as a non-homogeneous
Poisson process whose instantaneous rate is the scenario's per-axis demand
(``AxisDemand.rate_at``); each arrival is assigned a turn from ``turn_split`` and
routed across the intersection.

**Determinism contract** (unity-sumo-integration.md §Determinism, repro B-series):
seed a single ``random.Random(seed)``, emit **explicit ``<vehicle>`` elements**
(never ``<flow>``) sorted by departure time, with fixed float formatting. Same
``(scenario, seed)`` -> byte-identical file. This is what makes the JSONL traces
downstream reproducible.

Geometry (which approach+turn leads where, and which lane carries it) is reused
from :mod:`scripts.build_network` so there is a single source of truth.

Run::

    python -m scripts.build_routes                 # all scenarios x all seeds
    python -m scripts.build_routes --scenario SCN-02 --seed 0
"""

from __future__ import annotations

import argparse
import random
import sys
from dataclasses import dataclass
from pathlib import Path

import traci
from sumolib import checkBinary

from scripts.build_network import (
    GEOMETRY,
    IN_EDGE,
    LANE_FOR_TURN,
    OUT_EDGE,
    _NET_FILE,
    build_net,
)
from src.scenarios.config import AxisDemand, Scenario, load_all, load_scenario

_REPO_ROOT = Path(__file__).resolve().parent.parent
_ROUTES_DIR = _REPO_ROOT / "config" / "routes"

# Each approach belongs to one demand axis; both approaches on an axis emit at
# that axis's rate (N and S each at the N/S rate). ASSUMPTION: the demand table
# is per-approach, not split across the pair - see harsh-review / flag.
_APPROACH_AXIS: dict[str, str] = {"N": "ns", "E": "ew", "S": "ns", "W": "ew"}
_TURN_ORDER = ("left", "through", "right")  # fixed iteration order = determinism


@dataclass(frozen=True)
class Trip:
    """One generated vehicle: when it departs, where it enters, and its turn."""

    depart: float
    approach: str
    turn: str

    @property
    def route_edges(self) -> str:
        """The two-edge route ``"<in_edge> <out_edge>"`` across the junction."""
        dest = GEOMETRY[(self.approach, self.turn)]
        return f"{IN_EDGE[self.approach]} {OUT_EDGE[dest]}"

    @property
    def depart_lane(self) -> int:
        """Lane index this turn must depart from (left=2, through=1, right=0)."""
        return LANE_FOR_TURN[self.turn]


def _lambda_max(demand: AxisDemand, duration: int) -> float:
    """Upper bound on the arrival rate over ``[0, duration]`` (grid scan, 1 s)."""
    return max(demand.rate_at(float(t)) for t in range(0, duration + 1))


def _sample_turn(rng: random.Random, turn_split: dict[str, float]) -> str:
    """Pick a turn from the split (fixed cumulative order for reproducibility)."""
    r = rng.random()
    cum = 0.0
    for turn in _TURN_ORDER:
        cum += turn_split[turn]
        if r <= cum:
            return turn
    return _TURN_ORDER[-1]  # float-rounding fallback


def generate_trips(scenario: Scenario, seed: int) -> list[Trip]:
    """Generate the sorted vehicle list for one ``(scenario, seed)``.

    Non-homogeneous Poisson via thinning: propose arrivals at the per-approach
    ``lambda_max`` and accept each with probability ``rate_at(t) / lambda_max``.
    """
    rng = random.Random(seed)
    trips: list[Trip] = []
    for approach, axis in sorted(_APPROACH_AXIS.items()):  # deterministic order
        demand = scenario.ns if axis == "ns" else scenario.ew
        lam_max = _lambda_max(demand, scenario.duration_s)
        if lam_max <= 0:
            continue
        t = 0.0
        while True:
            t += rng.expovariate(lam_max / 3600.0)  # vph -> veh/s
            if t >= scenario.duration_s:
                break
            if rng.random() <= demand.rate_at(t) / lam_max:
                trips.append(Trip(depart=t, approach=approach, turn=_sample_turn(rng, scenario.turn_split)))
    # SUMO requires depart-sorted vehicles; tie-break for byte-stable ordering.
    trips.sort(key=lambda tr: (tr.depart, tr.approach, tr.turn))
    return trips


def _route_xml(scenario: Scenario, seed: int, trips: list[Trip]) -> str:
    """Render the ``.rou.xml`` text (fixed formatting -> byte-reproducible)."""
    lines = [
        f"<!-- generated by scripts/build_routes.py (T-01-08): {scenario.id} seed {seed}. "
        "Do not edit by hand; regenerate. -->",
        "<routes>",
        f'    <vType id="{scenario.vehicle_type}" vClass="passenger"/>',
    ]
    for i, tr in enumerate(trips):
        lines.append(
            f'    <vehicle id="v{i}" type="{scenario.vehicle_type}" depart="{tr.depart:.2f}" '
            f'departLane="{tr.depart_lane}" departSpeed="max">'
        )
        lines.append(f'        <route edges="{tr.route_edges}"/>')
        lines.append("    </vehicle>")
    lines.append("</routes>")
    return "\n".join(lines) + "\n"


def write_routes(scenario: Scenario, seed: int, out_dir: Path = _ROUTES_DIR) -> Path:
    """Generate and write one route file; returns its path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    trips = generate_trips(scenario, seed)
    scn_num = scenario.id.split("-")[1]
    out_path = out_dir / f"scn_{scn_num}_seed_{seed:02d}.rou.xml"
    out_path.write_text(_route_xml(scenario, seed, trips), encoding="utf-8")
    return out_path


def main() -> None:
    """Generate route files for the requested scenarios x seeds."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scenario", help="single scenario id (e.g. SCN-02); default all")
    parser.add_argument("--seed", type=int, help="single seed; default all in the scenario")
    args = parser.parse_args()

    scenarios = [load_scenario(_REPO_ROOT / "config" / "scenarios"
                               / f"scn_{args.scenario.split('-')[1]}.yaml")] if args.scenario else load_all()

    total = 0
    for scenario in scenarios:
        seeds = [args.seed] if args.seed is not None else scenario.seeds
        for seed in seeds:
            path = write_routes(scenario, seed)
            n = sum(1 for _ in path.read_text(encoding="utf-8").splitlines() if "<vehicle " in _)
            print(f"[routes] {scenario.id} seed {seed:02d} -> {path.relative_to(_REPO_ROOT)} ({n} vehicles)")
            total += 1
    print(f"[routes] OK - wrote {total} route file(s).")
    sys.exit(0)


if __name__ == "__main__":
    main()
